SELECT 
S_PRJNO,
DL_BUDTOLCOS,
 DL_BUDLABAMT,
DL_BUDCOSAMT,
DL_BUDPURAMT,
DL_INITCRYOR,
DL_MAINSRTAX,
DL_BUDTOLCOS - DL_BUDLABAMT - DL_BUDCOSAMT - DL_BUDPURAMT - DL_INITCRYOR - DL_MAINSRTAX
from mdl_aos_project
where DL_BUDTOLCOS != DL_BUDLABAMT + DL_BUDCOSAMT + DL_BUDPURAMT + DL_INITCRYOR + DL_MAINSRTAX
and id = 151940
-- 预算总成本 = 预算人力成本+预算费用成本+预算采购成本+16年期初实际成本+附加税金
;
-- 预算总成本:29309435.24000

SELECT
I_PRJID, ORIGINID, sum(DL_INSUMAMT)
from mdl_aos_prpurchas_his
where IS_DELETE=0
and I_PRJID = 151940
GROUP BY I_PRJID, ORIGINID;
-- 采购：4220000.00000


SELECT 
-- a.I_PRJID, a.S_PYEARMON, a.ID,
-- DL_PLABTLFEE `计划人力成本`, DL_PROOMFEE `计划费用成本`, DL_RLABTLFEE `实际人力成本`,
-- DL_RTOTALFEE `实际费用`
SUM(case when S_PYEARMON>201905 then DL_PLABTLFEE else DL_RLABTLFEE end) `人力`, 
SUM(DL_RLABTLFEE),
SUM(DL_PLABTLFEE),
SUM(case when S_PYEARMON>201905 then DL_PROOMFEE else DL_RTOTALFEE end) `费用`
FROM mdl_aos_prmonthpl a
where 1=1 and IS_DELETE = 0
and a.I_PRJID = 151940
ORDER BY a.I_PRJID, S_PYEARMON;
-- 人力：23741487.00000
-- 费用: 65437.62000