SELECT
FIACCFLOW.S_FLOWCODE `账户流水编码`,
FIACCADM.S_BANKACT `账户`,
COMPCODE.S_COMPNAME `财务主体`,
(SELECT DICT_NAME from PLF_AOS_DICTIONARY where DICT_CODE = FIACCFLOW.S_FLOWSTATE and DICT_TYPE = 'TradSte') `流水状态`,
date_format(FIACCFLOW.DT_OCCURDATE,'%Y-%m-%d') `费用发生日期`,
case FIACCFLOW.S_MNYFLOW when 's' then '收' when 'f' then '付' end `资金流向`,
case when FIACCFLOW.S_FLOWBUSIN='sr' or FIACCFLOW.S_FLOWBUSIN='fr' then '日常运营' 
		when FIACCFLOW.S_FLOWBUSIN='sc' or FIACCFLOW.S_FLOWBUSIN='fc' then '筹资' 
		when FIACCFLOW.S_FLOWBUSIN='st' or FIACCFLOW.S_FLOWBUSIN='ft' then '投资' end `款项类型`,

(SELECT DICT_NAME from PLF_AOS_DICTIONARY where DICT_CODE = FIACCFLOW.S_FLOWMONEY and DICT_TYPE = 'flowMoney') `款项种类`,
FIACCFLOW.DL_AMOUNT `金额`,
(SELECT DICT_NAME from PLF_AOS_DICTIONARY where DICT_CODE = FIACCADM.S_CURRENCY and DICT_TYPE = 'CURRENCY') `币种`,
SACUSTINF.S_CUSTNAME `客户`,
-- (SELECT S_CUSTNAME from mdl_aos_sacustinf where ID = FIACCFLOW.I_CUSTOMID) `客户`,
U.REAL_NAME `员工`,
-- (SELECT REAL_NAME from plf_aos_auth_user where ID = FIACCFLOW.S_STAFFID) `员工`,
PUSUPLIE.S_SUPNAME `供应商`,
-- (SELECT S_SUPNAME from MDL_AOS_PUSUPLIE where id = FIACCFLOW.I_SUPLIERID) `供应商`,
FIACCFLOW.S_CONTCUNIT `其他收/付款单位`,
case FIACCFLOW.S_YNALLOT when 1 then '否' when 2 then '是' end `是否需要分配`,
FIACCFLOW.S_REMARKS `摘要`,
U2.REAL_NAME `流水登记人`
-- (SELECT REAL_NAME from plf_aos_auth_user where USER_CODE = FIACCFLOW.C_USER_CODE) `流水登记人`
FROM MDL_AOS_FIACCFLOW FIACCFLOW
LEFT JOIN MDL_AOS_COMPCODE AS COMPCODE ON FIACCFLOW.I_FCBODY = COMPCODE.ID
LEFT JOIN MDL_AOS_FIACCADM AS FIACCADM ON FIACCFLOW.I_ACCOPERID = FIACCADM.ID
LEFT JOIN MDL_AOS_SACUSTINF AS SACUSTINF ON FIACCFLOW.I_CUSTOMID = SACUSTINF.ID
LEFT JOIN MDL_AOS_PUSUPLIE AS PUSUPLIE ON FIACCFLOW.I_SUPLIERID = PUSUPLIE.ID 
LEFT JOIN PLF_AOS_AUTH_USER U on U.ID=FIACCFLOW.S_STAFFID
LEFT JOIN PLF_AOS_AUTH_USER U2 on U2.USER_CODE=FIACCFLOW.C_USER_CODE
WHERE FIACCFLOW.IS_DELETE = 0
ORDER BY FIACCFLOW.DT_OCCURDATE DESC