SELECT FITRADEIF.CREATE_TIME, FITRADEIF.ID AS ID, FITRADEIF.ID AS FITRADEIF_ID, FITRADEIF.S_BUSNUM AS FITRADEIF_S_BUSNUM, FITRADEIF.S_SOURCEKD AS FITRADEIF_S_SOURCEKD, 
(SELECT SourceKd_.DICT_NAME FROM PLF_AOS_DICTIONARY AS SourceKd_ WHERE DICT_TYPE = 'SourceKd' AND SourceKd_.DICT_CODE = FITRADEIF.S_SOURCEKD) AS FITRADEIF_S_SOURCEKD_DNAME, FITRADEIF.S_SRCNUM AS FITRADEIF_S_SRCNUM, FITRADEIF.S_FINANCODE AS FITRADEIF_S_FINANCODE, FITRADEIF.DL_REALSUM AS FITRADEIF_DL_REALSUM, FITRADEIF.DT_RCDDATE AS FITRADEIF_DT_RCDDATE, FITRADEIF.S_TRADSTE AS FITRADEIF_S_TRADSTE, 
(SELECT TradSte_.DICT_NAME FROM PLF_AOS_DICTIONARY AS TradSte_ WHERE DICT_TYPE = 'TradSte' AND TradSte_.DICT_CODE = FITRADEIF.S_TRADSTE) AS FITRADEIF_S_TRADSTE_DNAME, FITRADEIF.DT_TALLYDATE AS FITRADEIF_DT_TALLYDATE, FITRADEIF.S_TALLYMAN AS FITRADEIF_S_TALLYMAN, 
(SELECT REAL_NAME FROM PLF_AOS_AUTH_USER U WHERE U.ID = FITRADEIF.S_TALLYMAN) AS FITRADEIF_S_TALLYMAN_UNAME, FITRADEIF.DT_TALOPDATE AS FITRADEIF_DT_TALOPDATE, COMPCODE.S_COMPNAME AS FITRADEIF_S_FINANCODE_RNAME 
FROM MDL_AOS_FITRADEIF AS FITRADEIF 
LEFT OUTER JOIN MDL_AOS_COMPCODE AS COMPCODE ON FITRADEIF.S_FINANCODE = COMPCODE.ID 
WHERE 1=1
-- and FITRADEIF.ENT_CODE = ? 
-- AND FITRADEIF.IS_DELETE = ? 
AND (FITRADEIF.S_TRADSTE = '08' OR FITRADEIF.S_TRADSTE = '04') 
ORDER BY CREATE_TIME DESC 
-- limit ?